name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: package.json

    - name: Install dependencies
      run: |
        npm install
        npm install -g hexo-cli

    - name: Fix file upate data
      run: |
        git ls-files -z | while read -d '' path; do touch -d $(git log -1 --format="@%ct" "$path") "$path" && echo "Fixed: $path"; done

    - name: Build Hexo
      run: hexo generate  # 生成站点

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public